-- =============================================================================
-- MÓDULO DE GESTIÓN DE ÁREAS
-- Permite sectorizar los cargos en Áreas (Admin, Comercial, Ops, etc.)
-- =============================================================================

-- 1. Crear tabla de Áreas
CREATE TABLE IF NOT EXISTS public.areas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Vincular Cargos con Áreas
-- Agregamos la columna area_id a job_positions
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'job_positions' AND column_name = 'area_id') THEN
        ALTER TABLE public.job_positions ADD COLUMN area_id BIGINT REFERENCES public.areas(id);
    END IF;
END $$;

-- 3. Insertar Áreas por Defecto
INSERT INTO public.areas (name) VALUES 
('ADMINISTRATIVO'), 
('COMERCIAL'), 
('FINANZAS'), 
('GENTE'), 
('MEJORA CONTÍNUA'),
('OPERACIONES') -- Agregado basado en el ejemplo del usuario
ON CONFLICT (name) DO NOTHING;

-- 4. Habilitar RLS (Opcional, pero recomendado)
ALTER TABLE public.areas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Áreas visibles para todos" ON public.areas
    FOR SELECT USING (true);

CREATE POLICY "Admin gestiona áreas" ON public.areas
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM employees 
            WHERE employees.email = auth.email() 
            AND employees.role IN ('ADMIN', 'SUPER ADMIN')
        )
    );
